version: "3"
services:
 node-app:
  volumes:
    - ./src:/app/src:ro
  build:
    context: .
    args: 
     - NODE_ENV=production
  environment:
    - NODE_ENV=development
  command: npm run start-dev  